name: Release Please (Develop)

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config-develop.json
          manifest-file: .release-please-manifest-develop.json
          target-branch: develop
